### ISSUE TITLE
Possible code simplification

### ISSUE THREAD

**Issue by CeType** [fotisk07/SI-Project#10]
**_Created a pull request:_** #12 

Maybe this part of the code could be simplified:
https://github.com/fotisk07/SI-Project/blob/32c99d189db3fd56a5d13a393c488627a1c7a5a3/Mapping/LiSim/sim.py#L43-L50

by replacing 
``` python 
self.current_ray
``` 

with 

```python
current_ray
``` 
and removing the except statement.

**Comment by CeType** [comment]
Maybe there's a purpose to it, but just in case it's a slip

**Comment by fotisk07** [comment]
Did you test it?

**Comment by CeType** [comment]
I have, as is, the block always raises an "Attribute Exception" because of the `self.current_ray` so the catch statement is always called. Removing the try statement is thus giving the exact same result

**Comment by fotisk07** [comment]
Ok then
