### ISSUE TITLE
Peculiar behaviour at LiDAR 

### ISSUE THREAD

**Issue by CeType** [fotisk07/SI-Project#11]
The value attached to the LiDAR's own position is surprisingly high, as can be seen in this output:

[Log4.txt](https://github.com/fotisk07/SI-Project/files/3774867/Log4.txt)

**Comment by CeType** [comment]
Sorry I didn't notice 
``` python
carte[5][5] = 1000
```

But why do so ?

**Comment by fotisk07** [comment]
Just to be able to easily see where the lidar position is
