### ISSUE TITLE
Noise Function indices are high

### ISSUE THREAD

**Issue by fotisk07** [fotisk07/SI-Project#13]
At the boundaries, adding noise caused the indexes to go out of bound

**Comment by fotisk07** [comment]
I'm too bored to fix it now

**Comment by CeType** [comment]
I believe that's more of a functionality addition than a bugfix

What we want is that at some fixed "horizon" distance, the results be capped

**Comment by fotisk07** [comment]
Yes I know but im too bored to do it now, ill do it tomorrow

**Comment by fotisk07** [comment]
The new commit handles this issue
