### ISSUE TITLE
Theres is little to no noise added in the top of the map

### ISSUE THREAD

**Issue by fotisk07** [fotisk07/SI-Project#25]
![Produced-Map](https://user-images.githubusercontent.com/32436069/67755390-57d1f180-fa38-11e9-8b9b-de4ece080ccb.png)
![Produced-Map](https://user-images.githubusercontent.com/32436069/67755481-8780f980-fa38-11e9-80e0-1f298c41e224.png)

Doesn't seem like just a random thing

**Comment by CeType** [comment]
I believe its the measurement density that is higher because the lidar is closer
So it must be more accurate

**Comment by CeType** [comment]
If you put the LiDar in center, it becomes way nicer

**Comment by fotisk07** [comment]
riiight
