### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by CeType** [fotisk07/SI-Project#28]
- Discussion about the (in progress as I understand) implementation of the command line interface for the project.

_Please reference this issue in commits or pull requests aiming to implement/solve the discussed topic so as to close this issue when merged into master._

**Comment by fotisk07** [comment]
I will eventually start to work on it

**Comment by CeType** [comment]
GitHub doesn't  want to put you on top

**Comment by fotisk07** [comment]
maybe it's an alphabetical order thingy
