### ISSUE TITLE
Animating the LiDAR result plots

### ISSUE THREAD

**Issue by CeType** [fotisk07/SI-Project#30]
- Show the progression in time of the LiDAR's measurements as it processes more and more data points. Could benefit from #29 by giving a realistic way to redraw the graphics

_Please reference this issue in commits or pull requests aiming to implement/solve the discussed topic so as to close this issue when merged into master._

**Comment by fotisk07** [comment]
I'm working on it

**Comment by CeType** [comment]
I know, it's for organisation purposes, according to GitHub's guides, that's a good way of managing future features

**Comment by CeType** [comment]
The way I'd see it (and that I think would integrate well in the IRL port of LiMap) is maybe something with a loop (IRL LiMap in [])

->Get data from LiSim[Get data from serial buffer] 
-> Run the mapping with the previous map as starting point and the new data
-> Redraw graphics
-> loop

But that's only a suggestion, you're free to do whatever you want with it (use it fully, partially, discard it fully)

**Comment by fotisk07** [comment]
The way my simulation is supposed to work is the following:
--> Get data from Lisim
--> Run the mapping script and save the current map in a directory
--> A program running parallelly will use the saved current map and draw it
--> Loop

**Comment by fotisk07** [comment]
So yeah I guess it's gonna work pretty much the way you imagined it

**Comment by CeType** [comment]
Couldn’t that be problematic for the IRL version ? I mean there must be a pretty heavy I/O overhead from using a file as an exchange thingy

**Comment by CeType** [comment]
Plus possibly overhead from ensuring data integrity

**Comment by fotisk07** [comment]
maybe but I don't see a better way especially with those shitty libraries

**Comment by CeType** [comment]
Can you publish your working branch so I can tekkaluk ?

**Comment by fotisk07** [comment]
Sure

**Comment by fotisk07** [comment]
It's not finished and i'm taking a break rn so it's tagnled but you can have a go

**Comment by CeType** [comment]
Oki

**Comment by CeType** [comment]
I'm completely unable to work on this, Mac OS refuses to draw any dynamic PyPlot thingies, I have tried one of the bazillions of semi-solutions on SO but none worked. This seems to be a recurring problem sooo... I'll try to look more into it later

**Comment by CeType** [comment]
I can work on CLI stuff tho

**Comment by fotisk07** [comment]
I'm telling you dude I HATE ANIMATION

**Comment by fotisk07** [comment]
I think I will maybe have a working solution by tonight (depends and when Madison will be back 😉

**Comment by fotisk07** [comment]
That's good i was thinking of doing that sometime. Use argparse it's pretty straighforward

**Comment by CeType** [comment]
Yep I know

**Comment by fotisk07** [comment]
After some CONSIDERABLE AMOUNT OF WORK, I have an animation up and running!

**Comment by fotisk07** [comment]
There are some bugs, but i don't think they are due to the animation file

**Comment by CeType** [comment]
I bet it simply won’t work on my machine... I’ll try to find a Mac OS specific workaround
