### ISSUE TITLE
Lidar animation is not real time

### ISSUE THREAD

**Issue by fotisk07** [fotisk07/SI-Project#31]
The animate module can't simulate when data come in real time, the index i is for to big for the img array

**Comment by CeType** [comment]
I have worked on a tool to break down the data in batches of a random number of points (you can set a maximum batch length), ie. #29 
Would that help ?

**Comment by CeType** [comment]
Anyway let’s sleep

**Comment by fotisk07** [comment]
not really I just need to find a smart solution to deal with their shitty library

**Comment by fotisk07** [comment]
IM AWESOME IM AWESOME IMA AWSEOME
