### ISSUE TITLE
When I run the code I get the error Scheduler takes 0 positional argument but none were given

### ISSUE THREAD

**Issue by fotisk07** [fotisk07/SI-Project#37]
When I run the code I get the error Scheduler takes 0 positional argument but none were given

_Originally posted by @fotisk07 in https://github.com/fotisk07/SI-Project/pull/32#issuecomment-547956960_

**Comment by CeType** [comment]
mmmh

**Comment by CeType** [comment]
Does it fail on Scheduler() or on getNextBatch() ?

**Comment by CeType** [comment]
Could I see the full error stack ?

**Comment by CeType** [comment]
I guess it's on getNextBatch() ?

**Comment by CeType** [comment]
May be lacking a lil self in da definition

**Comment by fotisk07** [comment]
I can't send you the full error stack because I am not running that instance any more

**Comment by fotisk07** [comment]
But yeah it fails on the getNextBatch

**Comment by CeType** [comment]
Does this help ?
