### ISSUE TITLE
Animation Black and white, small, and infinite loop

### ISSUE THREAD

**Issue by CeType** [fotisk07/SI-Project#43]
Trying to enable the -ani option results in a very small window (about 1.5 cm^2) and the plot being black and white. Besides, there is no way to stop the program other than killing the process.

**Comment by fotisk07** [comment]
It's normal, the animation displays an image and we are feeding in a 2d array with values from 0 to 255 so the image is bound to be black and white

**Comment by fotisk07** [comment]
To stop the program you press q a couple of times

**Comment by fotisk07** [comment]
And the animation is small because the array is small if you use bigger dim you get a bigger picture, if I scale it it becames uglu and not ncie

**Comment by fotisk07** [comment]
Latest commit makes the matplotlib plot nice and blue as they were before

**Comment by fotisk07** [comment]
I can write a colormap function that changes stuffs and makes the animation prettier i guess but not sure if the black and white is a huge nuissance

**Comment by fotisk07** [comment]
Last commit made the animation colorful, a special treat just for you!

**Comment by fotisk07** [comment]
Should I close the issue then?

**Comment by CeType** [comment]
Yay
